### ISSUE TITLE
有计划升级到新版电商SDK吗？

### ISSUE THREAD

**Issue by danieldai** [niugengyun/easytbk-flutter#1]
我从阿里百川的文档看到旧版百川电商SDK（版本号3.x.x.x及以下版本）会保留到2019年9月30日（不含）。2019年9月30日起（含），阿里百川电商SDK的旧版本服务将逐步停止。

请问这个插件有计划升级到新版的电商SDK吗？

https://baichuan.taobao.com/docs/doc.htm?spm=a3c0d.8115107.0.0&treeId=129&articleId=118171&docType=1

**Comment by niugengyun** [comment]
没有
